### ISSUE TITLE
what gui annotation tool is used for annotating streusle corpus ?

### ISSUE THREAD

**Issue by papasanimohansrinivas** [nert-nlp/streusle#86]
I want to extend streusle dataset . if possible can u provide links to tool or source code of annotation tool for labelling  new data @nschneid . I have gone through some of papers mentioning streusle but no annotation tool reference

**Comment by nschneid** [comment]
I'm afraid the quick-and-dirty annotation tool used for the original STREUSLE annotation in 2013-2014 is no longer usable. For maintaining the annotations since then we have been using spreadsheets and other text-based formats that get converted back to the .conllulex format.

I suggest taking a look at well-maintained open source tools for span annotation. These can probably be adapted for STREUSLE-style annotation.
